package me.rique.smpcore.util;

import java.util.Locale;
import java.util.Set;

public final class PluginCommandRoots {

    private static final Set<String> ROOTS = Set.of(
        "admin",
        "adminunvanish",
        "announce",
        "audititem",
        "back",
        "boss",
        "bosses",
        "bossbrews",
        "bossritual",
        "bossrituals",
        "bosspotions",
        "broadcast",
        "brews",
        "citem",
        "classinfo",
        "core",
        "customitem",
        "dashbook",
        "day",
        "deletehome",
        "delhome",
        "delicatebook",
        "djbook",
        "doublejumpbook",
        "ec",
        "enchantments",
        "enchants",
        "enderchest",
        "feed",
        "fly",
        "flyspeed",
        "forceunvanish",
        "gamemodeadventure",
        "gamemodecreative",
        "gamemodespectator",
        "gamemodesurvival",
        "gma",
        "gmc",
        "gmsp",
        "gms",
        "god",
        "guide",
        "heal",
        "help",
        "home",
        "homes",
        "invsee",
        "itemaudit",
        "itemtrace",
        "lb",
        "leaderboard",
        "leaderboards",
        "legendary",
        "lrecipe",
        "lrecipes",
        "menu",
        "msummon",
        "mythicfusions",
        "mythicnexus",
        "mythics",
        "nexus",
        "nick",
        "nickname",
        "night",
        "pardon",
        "powerinfo",
        "powermenu",
        "powerset",
        "reliquary",
        "removehome",
        "replenishbook",
        "revealplayer",
        "rituals",
        "sethome",
        "setpower",
        "setspawn",
        "shadow",
        "sclightning",
        "smeltingbook",
        "smeltingtouchbook",
        "smpcore",
        "smphelp",
        "smpmenu",
        "smpstart",
        "smpwiki",
        "spawn",
        "spawner",
        "spawnermgr",
        "speed",
        "startsmp",
        "storm",
        "stormcaller",
        "stormpower",
        "suicide",
        "sun",
        "team",
        "teams",
        "teamvault",
        "teamvaultsee",
        "telekenesisbook",
        "telekinesisbook",
        "top",
        "topstats",
        "travel",
        "tvault",
        "tvaultsee",
        "unban",
        "v",
        "vanish",
        "veinminer",
        "viewteamvault",
        "voidnv",
        "voidstep",
        "voidvision",
        "vm",
        "vstep",
        "vvision",
        "wiki",
        "wisebook",
        "wspeed",
        "xray"
    );

    private PluginCommandRoots() {
    }

    public static boolean contains(String root) {
        return root != null && ROOTS.contains(root.toLowerCase(Locale.ROOT));
    }
}
